name: Sync main back to develop

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout develop
        run: git checkout develop

      - name: Merge main into develop
        run: git merge origin/main --no-edit

      - name: Push changes
        run: git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
